version: '3.8'

services:
  webscraper:
    build:
      context: ./QuoteHuntScraper
    container_name: quotehunt.webscraper
    networks:
      - internal_network

  webapi:
    build:
      context: ./QuoteHuntWebAPI
    container_name: quotehunt.webapi
    ports:
      - "5208:5208"
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
